// Package repository holds the data access layer for the application.
//
// ProductRepository is the contract (interface) that defines the operations
// the use case expects from a product repository. The concrete implementation
// is in product_postgres.go, but the use case does not know that: it only sees
// the interface.
// The struct and its fields are PRIVATE (lowercase): its code is only exposed
// through the NewProductRepository factory, which returns the interface.
package repository

import (
	"context"      // cancellation/timeout propagated through the chain
	"database/sql" // official package: runs queries against the database
	"fmt"          // handles errors while keeping the cause with %w
	"log"          // Go's standard logger: traces each step of this layer

	"github.com/davi1985/go-api/internal/domain" // entity used by the operations
)

// postgresProductRepository is the type that "fulfills" the ProductRepository
// interface. The `*` in the field means it points to the *sql.DB (the pool)
// created in the db package by whoever assembles the app (main).
type postgresProductRepository struct {
	db *sql.DB // handle to the connection pool
}

// NewProductRepository is the repository "factory": it takes the *sql.DB and
// returns a value that satisfies the ProductRepository interface. Whoever
// calls it never needs to know the postgresProductRepository struct.
func NewProductRepository(db *sql.DB) ProductRepository {
	// `&` creates a pointer to the struct just built.
	return &postgresProductRepository{db: db}
}

// GetProducts fetches every product from the database.
// `(r *postgresProductRepository)` is the receiver: `r` is the current
// instance.
func (r *postgresProductRepository) GetProducts(ctx context.Context) ([]domain.Product, error) {
	// The SQL lives in a constant at the top — a raw string (backticks)
	// allows multi-line text. Always use constants for queries: easier to
	// read and easier to test from outside.
	const query = `SELECT id, product_name, price FROM product ORDER BY id`

	// Every layer logs its step with the [layer] prefix, so you can follow a
	// single request descending the pyramid in the terminal.
	log.Printf("[repository] GetProducts: executing SELECT")

	// QueryContext runs a SELECT. Notice the `ctx` is passed to the database:
	// if the request is canceled, the query is aborted along with it.
	rows, err := r.db.QueryContext(ctx, query)
	if err != nil {
		log.Printf("[repository] GetProducts: query failed: %v", err)
		return nil, fmt.Errorf("failed to query products: %w", err)
	}
	// CRITICAL: always close the rows, with defer. Forgetting this leaks pool
	// connections and the app "dies" little by little.
	defer rows.Close()

	// make([]domain.Product, 0) creates an empty NON-nil slice. The JSON
	// difference you expect: an empty slice becomes `[]`, a nil slice would
	// become `null`.
	products := make([]domain.Product, 0)
	for rows.Next() { // Next() moves to the next row; returns false when done
		var product domain.Product // declares a "zero" Product variable each iteration
		// Scan copies the column values into the fields, in the same order as
		// the SELECT. `&field` = memory address (pointer) of the field.
		if err := rows.Scan(&product.ID, &product.Name, &product.Price); err != nil {
			return nil, fmt.Errorf("failed to scan product: %w", err)
		}
		products = append(products, product) // append = JS "push" (no manual re-alloc)
	}

	// rows.Err() must be checked AFTER the loop: iteration can fail halfway.
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("failed to iterate products: %w", err)
	}

	log.Printf("[repository] GetProducts: %d product(s) returned", len(products))
	return products, nil // success: products ready
}

// CreateProduct inserts one product and returns the id the database generated.
func (r *postgresProductRepository) CreateProduct(ctx context.Context, product domain.Product) (int, error) {
	// $1 and $2 are POSITIONAL PARAMETERS of Postgres. We never concatenate
	// values into the string (that opens the door to SQL injection) — the
	// driver escapes the values safely.
	// RETURNING id returns the id generated by the SERIAL in the INSERT query
	// itself.
	const query = `INSERT INTO product (product_name, price) VALUES ($1, $2) RETURNING id`

	log.Printf("[repository] CreateProduct: inserting (name=%q price=%.2f)", product.Name, product.Price)

	var id int // Scan will deposit the returned id here
	// QueryRowContext is for queries that return ONE row (INSERT...RETURNING).
	if err := r.db.QueryRowContext(ctx, query, product.Name, product.Price).Scan(&id); err != nil {
		log.Printf("[repository] CreateProduct: insert failed: %v", err)
		return 0, fmt.Errorf("failed to create product: %w", err)
	}

	log.Printf("[repository] CreateProduct: database assigned id=%d", id)
	return id, nil // success: id generated by the database
}
