// Package repository defines the data access CONTRACTS (interfaces) and the
// concrete Postgres implementation (in product_postgres.go).
//
// Why keep the interface separate from the implementation?
//
//  1. The use case comes to depend on a "contract", not on a specific DB.
//  2. In tests, we swap the real implementation for a mock that satisfies
//     the same contract.
//  3. If tomorrow we change Postgres for something else, the use case
//     does not change at all.
//
// Frontend analogy: depending on a TypeScript contract/interface instead of
// importing a concrete networking module directly.
package repository

import (
	"context" // context propagated through the whole chain (cancellation/timeout)

	"github.com/davi1985/go-api/internal/domain" // uses the Product entity
)

// ProductRepository is the contract any product repository must fulfill to
// be used by the application.
//
// Note the pattern:
//   - NAME: verb + noun (GetProducts, CreateProduct)
//   - first parameter: always context.Context
//   - return: always (value_type, error) — the error comes "alongside" the value
type ProductRepository interface {
	// Lists every product. Returns a Product slice and an error.
	GetProducts(ctx context.Context) ([]domain.Product, error)
	// Creates a product and returns the id generated by the database.
	CreateProduct(ctx context.Context, product domain.Product) (int, error)
}
