// Package domain holds the business ENTITIES (the "domain model").
//
// Golden rule of the layered architecture: the domain must NOT import
// anything beyond the Go standard library. It knows no database, no HTTP,
// no gin. It is the "purest" layer of the application.
//
// Frontend analogy: these are the types/entities everyone shares
// (e.g. `interface Product`), but here with rules and no library deps.
package domain

import "errors"

// ErrInvalidProduct is a "sentinel error": a fixed error used as a
// comparison key. Whoever handles the error uses errors.Is(err,
// ErrInvalidProduct) to decide the HTTP status. Validation issue -> 400;
// anything else -> 500.
//
// (A sentinel is a constant guard value, sort of an error enum.)
var ErrInvalidProduct = errors.New("invalid product")

// Product is the Product entity. Translated to TypeScript:
//
//	export interface Product {
//	  id: number
//	  name: string
//	  price: number
//	}
//
// The `json:"name"` tags tell Go how the field shows up in / is parsed from
// JSON (right now the Go field Name is "name" in JSON, all lowercase).
type Product struct {
	ID    int     `json:"id"`    // id generated by the database (SERIAL auto-increment)
	Name  string  `json:"name"`  // product name
	Price float64 `json:"price"` // price (note: in a real DB prefer NUMERIC over float)
}

// Validate holds the entity's validation rules.
//
// `(p *Product)` is the RECEIVER: this is how Go defines "instance methods".
// `p` is the instance itself, like `this` in JS, but passed explicitly. The
// `*` means it is a pointer (changes reflect back on the original).
func (p *Product) Validate() error {
	// Simple validation with no framework dependency.
	if p.Name == "" {
		return errors.New("product name is required")
	}
	if p.Price < 0 {
		return errors.New("price cannot be negative")
	}
	return nil // nil = "no error"
}
